### ISSUE TITLE
Create a generic InputBox Component

### ISSUE THREAD

**Issue by irshadjsr21** [girlscript-blr/BuildWithGSBlr-Raahat#23]
- Create the component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- Create a generic input component which takes the following props:
     - label: Label of input 
     - id : unique key
     - type : “text” | “textarea” | “number” - Default is “text”
     - value: The current value of the input field
     - error: Error to be displayed like ‘Name is required’, Default is `null`.
     - onChange: `data => console.log(data)`, A Callback function which takes the new value of the input field as a parameter.
- The input field should display the provided `label` prop & have the unique id.
- The input field should be of the given `type` and have the `value` as it's current value.
- It should also display the given `error` if it is provided.
- It should call the `onChange` function when the input is changed.

For Design Reference [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=332%3A0)

For technical reference [Click Here](https://medium.com/javascript-in-plain-english/creating-a-generic-text-input-component-with-react-886e0cf90016)

**Location to save the component ```src->components->common->inputBox```**

**Comment by Denisqo** [comment]
I would like to work on this issue. Please assign me.

**Comment by irshadjsr21** [comment]
Hola Coder @Denisqo ! 
It's time to start working on the issue assigned to you⏳ 
Please raise the PR till `26th October`⏱ for getting evaluated. And don't forget to register at here: https://tinyurl.com/buildwithgsblr to earn the exciting badges🎖


Feel free to post your queries in the comments thread. 
Also, you can discuss at Google groups: codewithgsblr-forum@googlegroups.com or email us at girlscriptblr@gmail.com
