### ISSUE TITLE
Create a SurveyResult page and add routing

### ISSUE THREAD

**Issue by irshadjsr21** [girlscript-blr/BuildWithGSBlr-Raahat#25]
- Create a `SurveyResult` component with dummy `Hello World` text.
- Implement routing such that the `SurveyResult` component is displayed when the user visits the`/survey-result` route.

**Location to save the component ```src->components->surveyResult->surveyResult```**

**Comment by Gautam-Arora24** [comment]
May I work on this issue

**Comment by irshadjsr21** [comment]
Hola Coder @Gautam-Arora24 ! 
It's time to start working on the issue assigned to you⏳ 
Please raise the PR till `26th October`⏱ for getting evaluated. And don't forget to register at here: https://tinyurl.com/buildwithgsblr to earn the exciting badges🎖


Feel free to post your queries in the comments thread. 
Also, you can discuss at Google groups: codewithgsblr-forum@googlegroups.com or email us at girlscriptblr@gmail.com
