### ISSUE TITLE
Create a PieChart Component

### ISSUE THREAD

**Issue by irshadjsr21** [girlscript-blr/BuildWithGSBlr-Raahat#26]
- This component should use Chart.js 
- This component should create a chart of type: pie
- This component should take the following props
    - labels: list of strings
    - record: list of integer values to display as per labels
    - backgroundColour: list of colors as per the record list
    - title: The title of the chart
    - color: The color of the pie chart
- Create the component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- The `title` props value should be the title of the chart.

Reference Link(here Doughnut Chart is same as Pie Chart)
https://www.createwithdata.com/react-chartjs-dashboard/

For Design Reference [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=372%3A61)

**Location to save the component ```src->components->common->pieChart```**

**Comment by purnima143** [comment]
@irshadjsr21  Can I work on this issue?

**Comment by irshadjsr21** [comment]
Hola Coder @purnima143 ! 
It's time to start working on the issue assigned to you⏳ 
Please raise the PR till `26th October`⏱ for getting evaluated. And don't forget to register at here: https://tinyurl.com/buildwithgsblr to earn the exciting badges🎖


Feel free to post your queries in the comments thread. 
Also, you can discuss at Google groups: codewithgsblr-forum@googlegroups.com or email us at girlscriptblr@gmail.com

**Comment by purnima143** [comment]
@irshadjsr21 I have done with PR. Please check it...
