### ISSUE TITLE
Create a layout component

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#4]
It should take the following props.
- children : ReactNode

It should render Navbar component and Footer component.

In the middle it should render the `children`.

Use this component in the HomePage.

**Location to save the component ```src->components->common```**

**Comment by Kathuria** [comment]
Can I work on this?

**Comment by smilegupta** [comment]
Yes! @Kathuria You can do that way too! If you have any doubts or you face any issues! Do drop a message on this thread

**Comment by Kathuria** [comment]
Sure, Thanks @smilegupta

**Comment by Kathuria** [comment]
Done, available in PR
