### ISSUE TITLE
Create a DB Class to mimic a Database.

### ISSUE THREAD

**Issue by irshadjsr21** [girlscript-blr/BuildWithGSBlr-Raahat#41]
This DB class will be used to mimic the functionalities of a Database by using the browser's `localStorage` API.

Create a `DB` class with the following features. 

- A Constructor.
    - It should take the following arguments `(key: string, schema: array)`.
    - The arguments should be validated to check if it contains the expected type of data as described below. 
        - `key` (**required**): It should be a non empty string. This key will be used to store the object in the localstorage. 
        - `schema` (**required**): It should be an array of strings. The array should not be empty. All the elements in the array are the fields (or columns) of the database. For example:

    ```json
    [
        "name",
        "age",
        "gender"
    ]
    ```
    - If the arguments are not of the expected type, it should throw an error. Otherwise it should store the two arguments in class variables.

- An `insert` method.
    - This method should take one argument `(entity: object)`.
    - The `entity` object should contain key-value pairs of `strings` only. For eg:
    ```json
    {
        "name": "John",
        "age": "45",
        "gender": "male"
    }
    ``` 
    - It should check if `entity` has all the fields present as mentioned in the `schema` otherwise throw an error.
    - It should also throw an error if there is any additional field in `entity` which is not specified in `schema`.
    - Now we need to store the `entity` in the `localStorage` with it's key as stored in the class variable `key`. There are two cases which we should keep in mind.
        - If there is no entry in the `localStorage` in the given `key`, then we should wrap the `entity` in an array, convert it to a string and store it in `localStorage`.
        - If there is an entry, then we get that entry, convert it from string to array, then append our entity to that array and resave it in the `localStorage`.

- A `findAll` method.
    - This takes no argument.
    - It gets the data from `localStorage` in the `key`, convert it from string to array and return it.

**Note**:
- When throwing an error, keep in mind to provide a meaningful message to it.

**Reference**:
- [Local Storage in React - Mosh](https://programmingwithmosh.com/react/localstorage-react/)
- [Local Storage API - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

**Location to save the `DB` class ```src->db->index.js```**

**Comment by Denisqo** [comment]
Hello @irshadjsr21, 

can I work on this issue?

**Comment by irshadjsr21** [comment]
Hola Coder @Denisqo ! 
It's time to start working on the issue assigned to you⏳ 
Please raise the PR till `13th November`⏱ for getting evaluated. And don't forget to register at here: https://tinyurl.com/buildwithgsblr to earn the exciting badges🎖


Feel free to post your queries in the comments thread. 
Also, you can discuss at Google groups: codewithgsblr-forum@googlegroups.com or email us at girlscriptblr@gmail.com
