### ISSUE TITLE
Create a Hero Component for the HomePage

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#5]
- Create the component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- Add this component in HomePage.

For Design Reference [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=5%3A29)

**Location to save the component ```src->components->home```**

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by smilegupta** [comment]
@purnima143 Yes
