### ISSUE TITLE
Create a TakeSurveyComponent for the HomePage

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#6]
- Create the component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- Add this component in HomePage

For Design Reference [Click here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=5%3A70)

**Location to save the component ```src->components->home```**

**Comment by Basilleaf24** [comment]
I would like to work on this.

**Comment by irshadjsr21** [comment]
@Basilleaf24 Go ahead!

**Comment by irshadjsr21** [comment]
Hey @Basilleaf24, You were assigned this issue on 3rd October and we're expecting a PR from you by 12th October. 
Please drop a comment here if you are facing any issues and we'll try to resolve it as soon as possible.
