### ISSUE TITLE
Create a SurveyResult for the HomePage

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#7]
- Create the component as shown in the design.
- The component should be responsive so that it looks good in both desktop and mobile view.
- Add this component in HomePage.

For Design Reference [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=5%3A93)

**Location to save the component ```src->components->home->surveyResult```**

**Comment by Basilleaf24** [comment]
I would like to work on this

**Comment by irshadjsr21** [comment]
Sorry @Basilleaf24, You can take up only one issue at a time. After you complete the assigned task, then you can take up another issue.

**Comment by Harshitha-sa** [comment]
Can i work on this?

**Comment by irshadjsr21** [comment]
Yes @Harshitha-sa !

**Comment by smilegupta** [comment]
Hey @Harshitha-sa , You were assigned this issue on 5rd October and we're expecting a PR from you by 13th October.
Please drop a comment here if you are facing any issues and we'll try to resolve it as soon as possible.

**Comment by smilegupta** [comment]
@Harshitha-sa  I left some comment on the PR, can you please have a look on it.
