### ISSUE TITLE
Create a modal component

### ISSUE THREAD

**Issue by smilegupta** [girlscript-blr/BuildWithGSBlr-Raahat#8]
This component should take the following props.
- isOpen: Boolean
- onClose: () => void
- title: String
- children: ReactNode

Create the component as shown in the design.
The modal should be displayed on top of the current page when `isOpen` is true.
The `title` props value should be the title of the modal.
The `children` props should be renders as the modal body.
The `onClose` function should be called when `x` is clicked. 

For Design Reference [Click Here](https://www.figma.com/file/TkpKfOPVtQ2XjADFp9Hhbz/Build-with-GS-BLR-Raahat?node-id=5%3A183)

**Location to save the component ```src->components->common```**

**Comment by rohit-kadam-hub** [comment]
can i work on this issue ?

**Comment by smilegupta** [comment]
@rohit-kadam-hub  Yes!

**Comment by rohit-kadam-hub** [comment]
How shall I connect you in case of any difficulties and support??

**Comment by rohit-kadam-hub** [comment]
#

**Comment by irshadjsr21** [comment]
If you have any queries, drop a comment on this issue. We'll get back to you as soon as we can.

**Comment by smilegupta** [comment]
Hey @rohit-kadam-hub , You were assigned this issue on 3rd October and we're expecting a PR from you by 12th October.
Please drop a comment here if you are facing any issues and we'll try to resolve it as soon as possible.

**Comment by rohit-kadam-hub** [comment]
i already pulled request yesterday itself

**Comment by rohit-kadam-hub** [comment]
Please review my PR asap

**Comment by rohit-kadam-hub** [comment]
@smilegupta please review my PR as soon as possible
